import "./globals.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-5">
      {/* <h1>Header</h1> */}
    {children}
      {/* <h1>Footer</h1> */}
      </body>
    </html>
  );
}
